language: python
cache:
  directories:
    - $HOME/.cache/pip
matrix:
  include:
    - python: 3.7
      env: TOXENV=docs
    - python: 3.6
      env: TOXENV=py36
install:
  - sudo apt install make
script:
  - make tests
